In [1]:
import os
import json
import numpy as np
import pandas as pd

In [2]:
FT_result_dir = os.path.join("..","results","EFO_0003884",)

## Load the evaluaiton results file, its mentioend as json
with open(os.path.join(FT_result_dir, "evaluation_results","pinnacle_seed=1","pinnacle_EFO_0003884_results.csv"), "r") as f:
    eval_results = json.load(f)
eval_results.keys()

dict_keys(['ap', 'auroc'])

In [3]:
eval_results["auroc"]
celltype_auroc_df = pd.DataFrame.from_dict(eval_results["auroc"], orient="index", columns=["auroc"])
celltype_auroc_df = celltype_auroc_df.reset_index().rename(columns={"index":"cell_type"}).sort_values("auroc", ascending=False)
celltype_auroc_df.to_csv(os.path.join(FT_result_dir,"celltype_rank_auroc.csv"),index=False)
celltype_auroc_df.head()

     cell_type     auroc
10       sperm  0.645614
3   hepatocyte  0.555417
1   fibroblast  0.536111
8     monocyte  0.500000
0    adipocyte  0.472015

In [4]:
eval_results["ap"]
celltype_ap_df = pd.DataFrame.from_dict(eval_results["ap"], orient="index", columns=["ap"])
celltype_ap_df = celltype_ap_df.reset_index().rename(columns={"index":"cell_type"}).sort_values("ap", ascending=False)
celltype_ap_df.to_csv(os.path.join(FT_result_dir,"celltype_rank_apr_at_k.csv"),index=False)
celltype_ap_df.head(10)

       cell_type        ap
8       monocyte  0.253859
1     fibroblast  0.220115
3     hepatocyte  0.173322
4       ionocyte  0.159925
10         sperm  0.143690
0      adipocyte  0.114139
6     macrophage  0.113708
7     melanocyte  0.091416
5   keratinocyte  0.087110
9    plasmablast  0.073327

In [ ]:
celltype_ap_df

In [7]:
eval_results["ap"]

{'acinar cell of salivary gland': 0.06590281026823697,
 'adipocyte': 0.08813898630993178,
 'adventitial cell': 0.08189455075791655,
 'alveolar fibroblast': 0.06991253662610666,
 'artery endothelial cell': 0.09036543443692327,
 'b cell': 0.2176469516911688,
 'basal cell': 0.07570984710719168,
 'basal cell of prostate epithelium': 0.02774304659576957,
 'bladder urothelial cell': 0.057156218363581555,
 'bronchial smooth muscle cell': 0.08466917234425791,
 'bronchial vessel endothelial cell': 0.10084383767460867,
 'capillary endothelial cell': 0.17494405657566808,
 'cardiac endothelial cell': 0.11218270105519869,
 'cardiac muscle cell': 0.09298546314409142,
 'cd141-positive myeloid dendritic cell': 0.18197576200396476,
 'cd1c-positive myeloid dendritic cell': 0.12496779069699251,
 'cd24 neutrophil': 0.12864612421379018,
 'cd4-positive helper t cell': 0.17514693445962087,
 'cd4-positive, alpha-beta memory t cell': 0.41872629682083107,
 'cd8-positive, alpha-beta cytokine secreting effector t cell': 0.17683145706861012,
 'cd8-positive, alpha-beta cytotoxic t cell': 0.21050613478946276,
 'cell of skeletal muscle': 0.1293394935351484,
 'ciliary body': 0.0849777682292669,
 'ciliated cell': 0.07606087176425703,
 'ciliated epithelial cell': 0.1133327672144954,
 'classical monocyte': 0.1182222655060637,
 'club cell': 0.2690543369844564,
 'club cell of prostate epithelium': 0.13554962357613853,
 'conjunctival epithelial cell': 0.06815550844749133,
 'connective tissue cell': 0.06840925122617508,
 'corneal epithelial cell': 0.07746753764349709,
 'corneal keratocyte': 0.046878672598306484,
 'dendritic cell': 0.1515162538243074,
 'dn1 thymic pro-t cell': 0.20380138197623923,
 'dn3 thymocyte': 0.21237100742206794,
 'dn4 thymocyte': 0.1794487357950383,
 'double-positive, alpha-beta thymocyte': 0.1267800636592019,
 'duct epithelial cell': 0.055939360838261946,
 'duodenum glandular cell': 0.04684774078744067,
 'endothelial cell': 0.09661892750638061,
 'endothelial cell of artery': 0.11330342509911928,
 'endothelial cell of hepatic sinusoid': 0.060125493556610406,
 'endothelial cell of lymphatic vessel': 0.07750353832360407,
 'endothelial cell of vascular tree': 0.1404544253631053,
 'enterocyte of epithelium of large intestine': 0.27436613808896415,
 'enterocyte of epithelium of small intestine': 0.16498985464873722,
 'epithelial cell': 0.04848311625784141,
 'epithelial cell of lacrimal sac': 0.09061748752990266,
 'epithelial cell of uterus': 0.08208862171612122,
 'erythroid progenitor': 0.2037095511872332,
 'eye photoreceptor cell': 0.08260414121087142,
 'fast muscle cell': 0.13330156496823165,
 'fibroblast': 0.09738753435952492,
 'fibroblast of breast': 0.12672585315890272,
 'fibroblast of cardiac tissue': 0.1329122951425894,
 'goblet cell': 0.09549689280566406,
 'granulocyte': 0.123413999131356,
 'gut endothelial cell': 0.2982689014846092,
 'hematopoietic stem cell': 0.1468591308606607,
 'hepatocyte': 0.07616987945339074,
 'hillock cell of prostate epithelium': 0.36511447549696774,
 'hillock-club cell of prostate epithelium': 0.061879575412342624,
 'immature enterocyte': 0.057512793221118616,
 'immature natural killer cell': 0.16296046883090706,
 'immune cell': 0.15091250703854006,
 'intermediate monocyte': 0.1427594020189227,
 'intestinal crypt stem cell': 0.062327807746037245,
 'intestinal crypt stem cell of large intestine': 0.23353282165343875,
 'intestinal crypt stem cell of small intestine': 0.050114676237757595,
 'intestinal enteroendocrine cell': 0.08372872300855583,
 'intestinal tuft cell': 0.1235359018950164,
 'intrahepatic cholangiocyte': 0.08710236711888136,
 'ionocyte': 0.09097981505384044,
 'keratinocyte': 0.07198234149981966,
 'kidney epithelial cell': 0.09531353109967813,
 'lacrimal gland functional unit cell': 0.10767476447485157,
 'langerhans cell': 0.16196324457184727,
 'large intestine goblet cell': 0.1442738487720372,
 'limbal stem cell': 0.03819141441151919,
 'limbal stromal cell': 0.056498625298863375,
 'liver dendritic cell': 0.1707075062529544,
 'luminal cell of prostate epithelium': 0.0667907810484692,
 'luminal epithelial cell of mammary gland': 0.14078749602787505,
 'lung ciliated cell': 0.03977979040616738,
 'lung microvascular endothelial cell': 0.148878023021114,
 'lymphatic endothelial cell': 0.10001760147022147,
 'macrophage': 0.0896346941686664,
 'mature conventional dendritic cell': 0.26995481417204154,
 'mature enterocyte': 0.0860590248575675,
 'mature nk t cell': 0.1676383704777334,
 'medullary thymic epithelial cell': 0.06274243826625009,
 'melanocyte': 0.058640365936402365,
 'memory b cell': 0.1439528641048577,
 'mesenchymal stem cell': 0.10634757100868303,
 'mesothelial cell': 0.059515799600591085,
 'microglial cell': 0.16060682498928963,
 'monocyte': 0.12863461947817864,
 'mucus secreting cell': 0.054538558438427275,
 'muller cell': 0.2754123493984811,
 'muscle cell': 0.1517069138356863,
 'myeloid cell': 0.14449005637737242,
 'myeloid dendritic cell': 0.1231311433538787,
 'myeloid progenitor': 0.1097695999766647,
 'myoepithelial cell': 0.09596841398671345,
 'myofibroblast cell': 0.12759268093058096,
 'myometrial cell': 0.11490349933610566,
 'naive regulatory t cell': 0.1415647821673033,
 'naive thymus-derived cd4-positive, alpha-beta t cell': 0.2093954251844578,
 'nampt neutrophil': 0.13464502591360847,
 'nk cell': 0.23227222134302938,
 'non-classical monocyte': 0.15598386110821155,
 'ocular surface cell': 0.09587914918724025,
 'pancreatic acinar cell': 0.10345095644828219,
 'pancreatic alpha cell': 0.058006037302595674,
 'pancreatic beta cell': 0.06153635744086139,
 'pancreatic delta cell': 0.06424860261558424,
 'pancreatic ductal cell': 0.06298859956080557,
 'pancreatic pp cell': 0.06011434741539599,
 'pancreatic stellate cell': 0.11257048154347288,
 'paneth cell of epithelium of large intestine': 0.16473635752839813,
 'paneth cell of epithelium of small intestine': 0.0650252377080892,
 'pericyte cell': 0.13437488158483402,
 'plasma cell': 0.09638040443928028,
 'plasmablast': 0.22075875056384678,
 'plasmacytoid dendritic cell': 0.1762396016549572,
 'pulmonary ionocyte': 0.08282773305231042,
 'radial glial cell': 0.09402004429206243,
 'regulatory t cell': 0.1605064165189168,
 'respiratory goblet cell': 0.12425492656639131,
 'respiratory mucous cell': 0.0731446543979282,
 'retina horizontal cell': 0.13223581944753543,
 'retinal bipolar neuron': 0.1530338828889947,
 'retinal blood vessel endothelial cell': 0.18939443170924564,
 'retinal ganglion cell': 0.07593010165463925,
 'retinal pigment epithelial cell': 0.04150138141672101,
 'salivary gland cell': 0.07801720068358549,
 'schwann cell': 0.2085050189040394,
 'secretory cell': 0.07160774073585775,
 'serous cell of epithelium of bronchus': 0.05553913440283056,
 'serous cell of epithelium of trachea': 0.06713667140036596,
 'skeletal muscle satellite stem cell': 0.11796396648318233,
 'small intestine goblet cell': 0.10357698914841773,
 'smooth muscle cell': 0.10264189217536701,
 'sperm': 0.17165935920708886,
 'stromal cell': 0.09020945242626205,
 't follicular helper cell': 0.2094812714922758,
 'tendon cell': 0.06754805804891076,
 'tongue muscle cell': 0.10648659959452375,
 'tracheal goblet cell': 0.06664248054869881,
 'transit amplifying cell of large intestine': 0.13373645548560012,
 'transit amplifying cell of small intestine': 0.12977958012916127,
 'type i nk t cell': 0.23640419540590654,
 'type i pneumocyte': 0.10346168162499336,
 'type ii pneumocyte': 0.08045584674850524,
 'vascular associated smooth muscle cell': 0.09248766392827863,
 'vein endothelial cell': 0.17708239942312465}

In [9]:
FT_result_dir = os.path.join("..","results","EFO_0000685","model_outputs","pinnacle_seed=1")
csv_filenames_in_all = [i for i in os.listdir(FT_result_dir) if "_all_" in i]
csv_filenames_in_all

['pinnacle_all_preds_acinar cell of salivary gland.csv',
 'pinnacle_all_preds_adipocyte.csv',
 'pinnacle_all_preds_adventitial cell.csv',
 'pinnacle_all_preds_alveolar fibroblast.csv',
 'pinnacle_all_preds_artery endothelial cell.csv',
 'pinnacle_all_preds_b cell.csv',
 'pinnacle_all_preds_basal cell.csv',
 'pinnacle_all_preds_basal cell of prostate epithelium.csv',
 'pinnacle_all_preds_bladder urothelial cell.csv',
 'pinnacle_all_preds_bronchial smooth muscle cell.csv',
 'pinnacle_all_preds_bronchial vessel endothelial cell.csv',
 'pinnacle_all_preds_capillary endothelial cell.csv',
 'pinnacle_all_preds_cardiac endothelial cell.csv',
 'pinnacle_all_preds_cardiac muscle cell.csv',
 'pinnacle_all_preds_cd141-positive myeloid dendritic cell.csv',
 'pinnacle_all_preds_cd1c-positive myeloid dendritic cell.csv',
 'pinnacle_all_preds_cd24 neutrophil.csv',
 'pinnacle_all_preds_cd4-positive helper t cell.csv',
 'pinnacle_all_preds_cd4-positive, alpha-beta memory t cell.csv',
 'pinnacle_all_preds_cd8-positive, alpha-beta cytokine secreting effector t cell.csv',
 'pinnacle_all_preds_cd8-positive, alpha-beta cytotoxic t cell.csv',
 'pinnacle_all_preds_cell of skeletal muscle.csv',
 'pinnacle_all_preds_ciliary body.csv',
 'pinnacle_all_preds_ciliated cell.csv',
 'pinnacle_all_preds_ciliated epithelial cell.csv',
 'pinnacle_all_preds_classical monocyte.csv',
 'pinnacle_all_preds_club cell.csv',
 'pinnacle_all_preds_club cell of prostate epithelium.csv',
 'pinnacle_all_preds_conjunctival epithelial cell.csv',
 'pinnacle_all_preds_connective tissue cell.csv',
 'pinnacle_all_preds_corneal epithelial cell.csv',
 'pinnacle_all_preds_corneal keratocyte.csv',
 'pinnacle_all_preds_dendritic cell.csv',
 'pinnacle_all_preds_dn1 thymic pro-t cell.csv',
 'pinnacle_all_preds_dn3 thymocyte.csv',
 'pinnacle_all_preds_dn4 thymocyte.csv',
 'pinnacle_all_preds_double-positive, alpha-beta thymocyte.csv',
 'pinnacle_all_preds_duct epithelial cell.csv',
 'pinnacle_all_preds_duodenum glandular cell.csv',
 'pinnacle_all_preds_endothelial cell.csv',
 'pinnacle_all_preds_endothelial cell of artery.csv',
 'pinnacle_all_preds_endothelial cell of hepatic sinusoid.csv',
 'pinnacle_all_preds_endothelial cell of lymphatic vessel.csv',
 'pinnacle_all_preds_endothelial cell of vascular tree.csv',
 'pinnacle_all_preds_enterocyte of epithelium of large intestine.csv',
 'pinnacle_all_preds_enterocyte of epithelium of small intestine.csv',
 'pinnacle_all_preds_epithelial cell.csv',
 'pinnacle_all_preds_epithelial cell of lacrimal sac.csv',
 'pinnacle_all_preds_epithelial cell of uterus.csv',
 'pinnacle_all_preds_erythroid progenitor.csv',
 'pinnacle_all_preds_eye photoreceptor cell.csv',
 'pinnacle_all_preds_fast muscle cell.csv',
 'pinnacle_all_preds_fibroblast.csv',
 'pinnacle_all_preds_fibroblast of breast.csv',
 'pinnacle_all_preds_fibroblast of cardiac tissue.csv',
 'pinnacle_all_preds_goblet cell.csv',
 'pinnacle_all_preds_granulocyte.csv',
 'pinnacle_all_preds_gut endothelial cell.csv',
 'pinnacle_all_preds_hematopoietic stem cell.csv',
 'pinnacle_all_preds_hepatocyte.csv',
 'pinnacle_all_preds_hillock cell of prostate epithelium.csv',
 'pinnacle_all_preds_hillock-club cell of prostate epithelium.csv',
 'pinnacle_all_preds_immature enterocyte.csv',
 'pinnacle_all_preds_immature natural killer cell.csv',
 'pinnacle_all_preds_immune cell.csv',
 'pinnacle_all_preds_intermediate monocyte.csv',
 'pinnacle_all_preds_intestinal crypt stem cell.csv',
 'pinnacle_all_preds_intestinal crypt stem cell of large intestine.csv',
 'pinnacle_all_preds_intestinal crypt stem cell of small intestine.csv',
 'pinnacle_all_preds_intestinal enteroendocrine cell.csv',
 'pinnacle_all_preds_intestinal tuft cell.csv',
 'pinnacle_all_preds_intrahepatic cholangiocyte.csv',
 'pinnacle_all_preds_ionocyte.csv',
 'pinnacle_all_preds_keratinocyte.csv',
 'pinnacle_all_preds_kidney epithelial cell.csv',
 'pinnacle_all_preds_lacrimal gland functional unit cell.csv',
 'pinnacle_all_preds_langerhans cell.csv',
 'pinnacle_all_preds_large intestine goblet cell.csv',
 'pinnacle_all_preds_limbal stem cell.csv',
 'pinnacle_all_preds_limbal stromal cell.csv',
 'pinnacle_all_preds_liver dendritic cell.csv',
 'pinnacle_all_preds_luminal cell of prostate epithelium.csv',
 'pinnacle_all_preds_luminal epithelial cell of mammary gland.csv',
 'pinnacle_all_preds_lung ciliated cell.csv',
 'pinnacle_all_preds_lung microvascular endothelial cell.csv',
 'pinnacle_all_preds_lymphatic endothelial cell.csv',
 'pinnacle_all_preds_macrophage.csv',
 'pinnacle_all_preds_mature conventional dendritic cell.csv',
 'pinnacle_all_preds_mature enterocyte.csv',
 'pinnacle_all_preds_mature nk t cell.csv',
 'pinnacle_all_preds_medullary thymic epithelial cell.csv',
 'pinnacle_all_preds_melanocyte.csv',
 'pinnacle_all_preds_memory b cell.csv',
 'pinnacle_all_preds_mesenchymal stem cell.csv',
 'pinnacle_all_preds_mesothelial cell.csv',
 'pinnacle_all_preds_microglial cell.csv',
 'pinnacle_all_preds_monocyte.csv',
 'pinnacle_all_preds_mucus secreting cell.csv',
 'pinnacle_all_preds_muller cell.csv',
 'pinnacle_all_preds_muscle cell.csv',
 'pinnacle_all_preds_myeloid cell.csv',
 'pinnacle_all_preds_myeloid dendritic cell.csv',
 'pinnacle_all_preds_myeloid progenitor.csv',
 'pinnacle_all_preds_myoepithelial cell.csv',
 'pinnacle_all_preds_myofibroblast cell.csv',
 'pinnacle_all_preds_myometrial cell.csv',
 'pinnacle_all_preds_naive regulatory t cell.csv',
 'pinnacle_all_preds_naive thymus-derived cd4-positive, alpha-beta t cell.csv',
 'pinnacle_all_preds_nampt neutrophil.csv',
 'pinnacle_all_preds_nk cell.csv',
 'pinnacle_all_preds_non-classical monocyte.csv',
 'pinnacle_all_preds_ocular surface cell.csv',
 'pinnacle_all_preds_pancreatic acinar cell.csv',
 'pinnacle_all_preds_pancreatic alpha cell.csv',
 'pinnacle_all_preds_pancreatic beta cell.csv',
 'pinnacle_all_preds_pancreatic delta cell.csv',
 'pinnacle_all_preds_pancreatic ductal cell.csv',
 'pinnacle_all_preds_pancreatic pp cell.csv',
 'pinnacle_all_preds_pancreatic stellate cell.csv',
 'pinnacle_all_preds_paneth cell of epithelium of large intestine.csv',
 'pinnacle_all_preds_paneth cell of epithelium of small intestine.csv',
 'pinnacle_all_preds_pericyte cell.csv',
 'pinnacle_all_preds_plasma cell.csv',
 'pinnacle_all_preds_plasmablast.csv',
 'pinnacle_all_preds_plasmacytoid dendritic cell.csv',
 'pinnacle_all_preds_pulmonary ionocyte.csv',
 'pinnacle_all_preds_radial glial cell.csv',
 'pinnacle_all_preds_regulatory t cell.csv',
 'pinnacle_all_preds_respiratory goblet cell.csv',
 'pinnacle_all_preds_respiratory mucous cell.csv',
 'pinnacle_all_preds_retina horizontal cell.csv',
 'pinnacle_all_preds_retinal bipolar neuron.csv',
 'pinnacle_all_preds_retinal blood vessel endothelial cell.csv',
 'pinnacle_all_preds_retinal ganglion cell.csv',
 'pinnacle_all_preds_retinal pigment epithelial cell.csv',
 'pinnacle_all_preds_salivary gland cell.csv',
 'pinnacle_all_preds_schwann cell.csv',
 'pinnacle_all_preds_secretory cell.csv',
 'pinnacle_all_preds_serous cell of epithelium of bronchus.csv',
 'pinnacle_all_preds_serous cell of epithelium of trachea.csv',
 'pinnacle_all_preds_skeletal muscle satellite stem cell.csv',
 'pinnacle_all_preds_small intestine goblet cell.csv',
 'pinnacle_all_preds_smooth muscle cell.csv',
 'pinnacle_all_preds_sperm.csv',
 'pinnacle_all_preds_stromal cell.csv',
 'pinnacle_all_preds_t follicular helper cell.csv',
 'pinnacle_all_preds_tendon cell.csv',
 'pinnacle_all_preds_tongue muscle cell.csv',
 'pinnacle_all_preds_tracheal goblet cell.csv',
 'pinnacle_all_preds_transit amplifying cell of large intestine.csv',
 'pinnacle_all_preds_transit amplifying cell of small intestine.csv',
 'pinnacle_all_preds_type i nk t cell.csv',
 'pinnacle_all_preds_type i pneumocyte.csv',
 'pinnacle_all_preds_type ii pneumocyte.csv',
 'pinnacle_all_preds_vascular associated smooth muscle cell.csv',
 'pinnacle_all_preds_vein endothelial cell.csv']

In [10]:
df = pd.read_csv(os.path.join(FT_result_dir, csv_filenames_in_all[0]))
df.head()

     y     preds    name   type
0  0.0  0.213222   EGLN3  train
1  0.0  0.128638  MAP3K1   test
2  0.0  0.116498   KCNQ1   test
3  0.0  0.106897   NUCB1   test
4  0.0  0.101982    RIC3  train

In [11]:
def gene_pred_extractor(csv_filename, gene_symbol="CDK6", BASE_PATH = FT_result_dir):
    df = pd.read_csv(os.path.join(BASE_PATH, csv_filename))
    cell_type_name = csv_filename.replace(".csv","").replace("pinnacle_all_preds_","")
    if gene_symbol in df["name"].values:
        score = df[df["name"] == gene_symbol]["preds"].values[0]
        return score, cell_type_name
    ## Cell does not have the gene
    else:
        return np.nan, cell_type_name

## use gene_pred_extractor with a custom gene_symbol and apply it to csv_filenames list. use map or apply to speed up things

gene_symbol = "JAK3"
results = list(map(lambda x: gene_pred_extractor(x, gene_symbol=gene_symbol), csv_filenames_in_all))
# convert the list which returns a tuple to a dataframe so that we can sort it
df_results = pd.DataFrame(results, columns=["score", "cell_type"])
## Sort by score in descending order
df_results = df_results.sort_values(by="score", ascending=False)
df_results.dropna(inplace=True)
df_results.reset_index(drop=True, inplace=True)
df_results.head()

      score                                  cell_type
0  0.236386  cd8-positive, alpha-beta cytotoxic t cell
1  0.209317                            microglial cell
2  0.128264                    naive regulatory t cell
3  0.126089                   t follicular helper cell
4  0.112337                          regulatory t cell

In [12]:
## Iterate through the filenames, load the CSV, add a column where the values will be the celltype name from the filename. Concatenate all the csvs
dfs = []
for csv_filename in csv_filenames_in_all:
    df = pd.read_csv(os.path.join(FT_result_dir, csv_filename))
    cell_type_name = csv_filename.replace(".csv","").replace("pinnacle_all_preds_","")
    df["cell_type"] = cell_type_name
    dfs.append(df)
df_all = pd.concat(dfs, ignore_index=True)

In [13]:
df_all.head()

     y     preds    name   type                      cell_type
0  0.0  0.213222   EGLN3  train  acinar cell of salivary gland
1  0.0  0.128638  MAP3K1   test  acinar cell of salivary gland
2  0.0  0.116498   KCNQ1   test  acinar cell of salivary gland
3  0.0  0.106897   NUCB1   test  acinar cell of salivary gland
4  0.0  0.101982    RIC3  train  acinar cell of salivary gland

In [14]:
## Groupby the name, for each groupped dataframe, find the row with greatest preds. make a df with these rows alone
df_best = df_all.loc[df_all.groupby("name")["preds"].idxmax()]
df_best = df_best.sort_values(by="preds", ascending=False)
df_best.head(20)

,y,preds,name,type,cell_type
13442,1.0,0.505330,TUBB3,test,enterocyte of epithelium of large intestine
47574,1.0,0.428548,PRIM2,train,type i nk t cell
13443,0.0,0.417561,MT-CO2,test,enterocyte of epithelium of large intestine
5913,0.0,0.406750,HGS,test,"cd8-positive, alpha-beta cytotoxic t cell"
13444,0.0,0.406527,CDC42BPG,val,enterocyte of epithelium of large intestine
47575,0.0,0.395735,SLAMF7,test,type i nk t cell
47576,0.0,0.395100,SNRK,test,type i nk t cell
37079,0.0,0.392107,SLC25A13,train,paneth cell of epithelium of large intestine
26796,0.0,0.387649,RFK,test,macrophage
26797,0.0,0.376021,ATOX1,test,macrophage
13445,1.0,0.371378,PPARG,train,enterocyte of epithelium of large intestine
5914,1.0,0.365132,MAPK11,train,"cd8-positive, alpha-beta cytotoxic t cell"
37713,1.0,0.363530,POLD2,train,pericyte cell
47577,1.0,0.361245,PRIM1,train,type i nk t cell
15533,1.0,0.361103,SCN4A,train,fast muscle cell
15534,0.0,0.357866,CAMK2A,train,fast muscle cell
17595,0.0,0.357333,CPT1A,train,hematopoietic stem cell
17596,1.0,0.352483,CRBN,train,hematopoietic stem cell
29640,1.0,0.343318,TNFSF13B,train,microglial cell
5915,0.0,0.342927,ADRB2,test,"cd8-positive, alpha-beta cytotoxic t cell"

	y	preds	name	type	cell_type
8400	1.0	0.544774	FGFR3	train	conjunctival epithelial cell
24030	0.0	0.529834	TNK1	test	large intestine goblet cell
24031	1.0	0.527707	MAPKAPK5	train	large intestine goblet cell
0	0.0	0.514637	SHMT1	test	acinar cell of salivary gland
1	0.0	0.504812	AZGP1	val	acinar cell of salivary gland
47574	1.0	0.497695	PRIM2	train	type i nk t cell
41710	0.0	0.479576	ALAS1	train	retinal ganglion cell
42613	0.0	0.465789	GJA1	train	schwann cell
16440	1.0	0.458395	POLA2	test	fibroblast of cardiac tissue
2919	1.0	0.455851	JAK2	train	bronchial smooth muscle cell