## About

This code is to explore the supporting files that are part \
of the finetuning process.

## Issues and fixing steps

The disease_drug_evidence_EFO_0000685.csv file has issue while loading it as csv. This is caused due to overflow in `clinicalStatus` where it has some terms that are going to the next column and pushing the other column values.

In [1]:
import pandas as pd
import json
import os

In [2]:
DATAPATH = os.path.join("..","data")
THERAPUTIC_TARGET = os.path.join(DATAPATH,"therapeutic_target_task")

In [ ]:
all_apr_df = pd.read_csv(os.path.join(THERAPUTIC_TARGET,"all_approved_oct2022.csv"))
## Working with RA
disease_drug_evidence_df = pd.read_csv(os.path.join(THERAPUTIC_TARGET,"disease_drug_evidence_EFO_0000685.csv"))

## Datasplit with name
with open(os.path.join(THERAPUTIC_TARGET,"data_split_EFO_0000685_name.json")) as f:
    RA_data_split_name = json.load(f)

## Datasplit with index
with open(os.path.join(THERAPUTIC_TARGET,"data_split_EFO_0000685.json")) as f:
    RA_data_split = json.load(f)

## This has the positive split with neg for target with celltype combination
with open(os.path.join(THERAPUTIC_TARGET,"negative_proteins_EFO_0000685.json")) as f:
    RA_data_negative = json.load(f)
## This has the positive split with pos for target with celltype combination
with open(os.path.join(THERAPUTIC_TARGET,"positive_proteins_EFO_0000685.json")) as f:
    RA_data_positive = json.load(f)

In [ ]:
## This has the train and test split with positive and negative labels

RA_data_split_name.keys()

dict_keys(['pos_train_names', 'pos_test_names', 'neg_train_names', 'neg_test_names'])

In [9]:
RA_data_split_name["pos_train_names"]

['CCR5',
 'IMPDH1',
 'PIKFYVE',
 'CRBN',
 'PDE4C',
 'ESR1',
 'NR3C1',
 'IL23A',
 'POLD2',
 'PTAFR',
 'ITGAV',
 'PTGER3',
 'MIF',
 'LTB',
 'RRM1',
 'PTGS2',
 'TNFSF13B',
 'PDE6A',
 'BCR',
 'PRIM2',
 'HMGCR',
 'ABL1',
 'IL17RA',
 'POLE',
 'PPARG',
 'SCN4A',
 'ATP4A',
 'IRAK4',
 'PDE3B',
 'PDE8B',
 'PTH1R',
 'PRIM1',
 'PDE4B',
 'JAK2',
 'MAP2K1',
 'TUBB6',
 'MS4A1',
 'LTA',
 'OPRD1',
 'ITGB3',
 'MAPKAPK5',
 'LTB4R',
 'CD86',
 'PDE9A',
 'TUBB4A',
 'CXCL10',
 'TLR7',
 'SLC6A4',
 'PIK3CD',
 'GUCY1B2',
 'GNRHR',
 'JAK1',
 'TUBB1',
 'IMPDH2',
 'SLC29A1',
 'IL1B',
 'ITK',
 'HRH2',
 'FGFR3',
 'MAPK11',
 'VDR',
 'BTK',
 'ITGAL',
 'SCN8A',
 'CD40LG',
 'DHFR',
 'DHODH',
 'KIT',
 'IL1R1',
 'TNFSF13',
 'ACE',
 'OPRK1',
 'TRAF3IP2',
 'PDGFRA']

In [10]:
RA_data_split_name["neg_train_names"]

['HTR2B',
 'HSD17B4',
 'NNMT',
 'TYMP',
 'CACNA1H',
 'FGG',
 'ATP1B3',
 'GC',
 'MAOB',
 'RPL4',
 'CLASP1',
 'BCL2',
 'GLRB',
 'TMLHE',
 'GABBR2',
 'RDH8',
 'SLC52A2',
 'CAMK1G',
 'IDH1',
 'S1PR4',
 'FABP2',
 'GCLM',
 'HIPK3',
 'BMPR2',
 'TFR2',
 'MT1G',
 'GABRA4',
 'IAPP',
 'GAA',
 'SNAP25',
 'FOLR1',
 'APLP2',
 'CD22',
 'HSD17B1',
 'ATP6V0D2',
 'PIK3C2B',
 'CD55',
 'DDX5',
 'OXTR',
 'HPD',
 'DRD5',
 'GRM8',
 'CACNA1B',
 'ADRA1B',
 'FPGS',
 'OGFOD2',
 'S1PR1',
 'SLC1A5',
 'CASR',
 'KLK1',
 'NUAK2',
 'EGLN3',
 'ATIC',
 'GPX6',
 'L1CAM',
 'ATP6V1E1',
 'ZYX',
 'PRKCI',
 'HM13',
 'MAPK10',
 'S100A12',
 'STK10',
 'KCNJ12',
 'DAPK2',
 'ATF5',
 'STK26',
 'SLC16A5',
 'RPS2',
 'LHCGR',
 'ASMT',
 'STMN4',
 'FXN',
 'HEXB',
 'MINK1',
 'CHUK',
 'SIK1',
 'IFNAR2',
 'FGF23',
 'ABCC1',
 'SPTLC2',
 'CALM2',
 'ASPA',
 'CAMK2A',
 'BST1',
 'RRM2',
 'PAICS',
 'ROCK2',
 'AQP1',
 'SLC22A11',
 'TAOK3',
 'FBN3',
 'GPT2',
 'HSPG2',
 'CAT',
 'TRPV2',
 'VAMP2',
 'MAP4K3',
 'PCCA',
 'S1PR5',
 'ASIC2',
 'IKBKE',
 'PTGES3',
 'MT-CO3',
 'GSK3B',
 'APOE',
 'GABRA6',
 'PDCD1',
 'EIF2AK1',
 'MPG',
 'HAGH',
 'HP1BP3',
 'RDH11',
 'OAT',
 'ABCC9',
 'HNF4G',
 'COX5A',
 'ADRA1A',
 'IVD',
 'GGCX',
 'GLP1R',
 'IGFBP7',
 'M6PR',
 'GRIN3A',
 'CSNK2A2',
 'HSP90B1',
 'GGPS1',
 'OGFOD1',
 'ANGPTL3',
 'GPHN',
 'SEMG1',
 'HDAC4',
 'EIF4A1',
 'PDE11A',
 'CHRNA7',
 'GCGR',
 'MYO3A',
 'KCNJ8',
 'MGST3',
 'SNCA',
 'TACSTD2',
 'SPTLC3',
 'PRKG2',
 'CLK3',
 'PPP3R1',
 'CDKL1',
 'P4HA1',
 'TRPM4',
 'DPEP1',
 'PRKCG',
 'CALCRL',
 'RET',
 'SYT2',
 'FYN',
 'SERPINB9',
 'SLCO1B3',
 'CDH5',
 'EPHB2',
 'PPP2CA',
 'RPS5',
 'ADRA2B',
 'TUBA4A',
 'CSAD',
 'GSK3A',
 'PLG',
 'STK3',
 'FOLR3',
 'MT2A',
 'RBP1',
 'DNMT1',
 'SLC12A1',
 'PC',
 'HMMR',
 'IGFALS',
 'GSTO2',
 'CSNK1A1',
 'S100A13',
 'SLC12A7',
 'NRXN1',
 'PCSK9',
 'GOT2',
 'RIPK1',
 'COX6A2',
 'RIC3',
 'ABAT',
 'CYB5R3',
 'NQO2',
 'BCAT2',
 'MPO',
 'CHRM2',
 'IGHG1',
 'LIMK2',
 'TLK2',
 'RIOK1',
 'TGFBR1',
 'MAP3K2',
 'ST3GAL5',
 'PAEP',
 'SLC7A11',
 'ALKBH2',
 'ASPG',
 'NR4A3',
 'ALDH3B1',
 'CASP1',
 'SEC14L4',
 'METAP2',
 'CCDC51',
 'CALR',
 'GNG2',
 'RYR1',
 'ATP2A1',
 'LIG1',
 'SFRP4',
 'MAPK15',
 'HDAC5',
 'ALDH1B1',
 'FGB',
 'LAYN',
 'POLE4',
 'ATP6V0E2',
 'CASK',
 'CHEK2',
 'MT1A',
 'BDNF',
 'HNRNPH3',
 'COX6C',
 'F8',
 'SLC25A13',
 'MCFD2',
 'ELOVL2',
 'MKNK2',
 'ATF4',
 'MAP4K2',
 'PDCD6',
 'SLC10A1',
 'CS',
 'KCNK1',
 'XIAP',
 'ODC1',
 'ENPEP',
 'ACHE',
 'MAP2K3',
 'SLC29A2',
 'IGLL1',
 'CAMK1',
 'SLC38A4',
 'CD163',
 'GRM5',
 'KRT16',
 'CACNG2',
 'HDGF',
 'PAH',
 'LSM6',
 'PAK4',
 'GLS2',
 'LIG3',
 'RPS28',
 'TESK1',
 'TAB1',
 'TTR',
 'PSME1',
 'KRT7',
 'NEK9',
 'CD33',
 'ITPR1',
 'CACNA1E',
 'MTTP',
 'PGAM1',
 'UTRN',
 'GNMT',
 'TAGLN2',
 'MYH9',
 'PON1',
 'APOC2',
 'RDH14',
 'SCO1',
 'RPS6',
 'PKN2',
 'PPP2CB',
 'PROS1',
 'HTT',
 'FGF2',
 'SLC1A2',
 'ATP6V1F',
 'OPRL1',
 'CDK15',
 'KRT14',
 'KCNMB1',
 'CALCR',
 'SERPINB3',
 'CFI',
 'MT-CO1',
 'PARP3',
 'PRKAG1',
 'MT1DP',
 'GUCY1A2',
 'ACAD8',
 'ITIH1',
 'TLK1',
 'CKB',
 'BDH1',
 'SEC14L2',
 'RPE65',
 'PGRMC1',
 'SCN1B',
 'KCNN4',
 'PTGFR',
 'ESRRA',
 'CHEK1',
 'BMPR1B',
 'PPCDC',
 'ULK1',
 'CYP1B1',
 'NAGA',
 'AANAT',
 'RIOK3',
 'HDAC2',
 'PZP',
 'PRKCA',
 'AADAT',
 'UGDH',
 'AURKB',
 'DYRK1B',
 'DARS2',
 'TLR8',
 'KCNQ2',
 'P3H1',
 'SRD5A1',
 'TESMIN',
 'HSD17B10',
 'SLC5A5',
 'ACVR1',
 'ITIH4',
 'C1QC',
 'TPH1',
 'RPS8',
 'ADCY1',
 'PHB2',
 'PTPRE',
 'MAP2',
 'FECH',
 'STK32A',
 'CAMK2D',
 'ELN',
 'PARP1',
 'HTR6',
 'TNFRSF8',
 'EIF2AK4',
 'GAST',
 'DAPK3',
 'AKR1C3',
 'TNNC1',
 'PRKAB2',
 'ADRB3',
 'PTK2B',
 'KLK3',
 'ELOVL4',
 'NEK3',
 'ADRA2C',
 'VAMP1',
 'RPS13',
 'MAPK1',
 'AMN',
 'CASQ2',
 'RARA',
 'SULT1E1',
 'PRKAA2',
 'ASPH',
 'HSD11B1',
 'KRT5',
 'PTK2',
 'SERPINB6',
 'MTR',
 'HDC',
 'TK2',
 'COX8A',
 'FARSA',
 'CAMLG',
 'ATP6V0D1',
 'HCN2',
 'F13A1',
 'AASS',
 'KCNB2',
 'IKBKB',
 'CACNA1A',
 'GANAB',
 'CTNS',
 'YWHAB',
 'ALDH1A2',
 'SCNN1G',
 'MAP3K11',
 'MST1R',
 'IRAK3',
 'MT1H',
 'PTGER2',
 'PTGR2',
 'CPB1',
 'SLC22A12',
 'HRNR',
 'PPARA',
 'TEK',
 'CDK2',
 'NAGLU',
 'ADRB1',
 'FFAR1',
 'POLB',
 'MCCC2',
 'PTK6',
 'PLOD2',
 'GART',
 'NEU1',
 'PTPN4',
 'NPR2',
 'GRIA4',
 'KCNC2',
 'CIB2',
 'ITIH2',
 'IGLC1',
 'ATP6V1B1',
 'DAO',
 'MAP3K3',
 'ENO1',
 'HINT1',
 'MAST1',
 'BMPR1A',
 'AAK1',
 'SCN4B',
 'RTCB',
 'PSMB1',
 'C8A',
 'TPM1',
 'DMD',
 'HSPB1',
 'ST14',
 'ATP6V1G1',
 'MSMO1',
 'PIK3C2G',
 'CHRM5',
 'FNTA',
 'KCNJ10',
 'STK24',
 'IL5RA',
 'SRPK2',
 'FTCD',
 'PGLYRP2',
 'SRSF1',
 'CD79B',
 'DCLK2',
 'STAT5B',
 'GP9',
 'RDH12',
 'CSNK1E',
 'SDSL',
 'GFER',
 'S100A1',
 'CDK17',
 'CPT1A',
 'XDH',
 'SRSF4',
 'THRA',
 'TLR2',
 'SLC15A2',
 'PTS',
 'TYRO3',
 'GAD1',
 'CARTPT',
 'HRG',
 'CYCS',
 'S1PR3',
 'ADCY5',
 'CLU',
 'LEPR',
 'DGKA',
 'CACNA2D3',
 'CHP1',
 'CBR1',
 'ATP6V1C2',
 'CSN3',
 'SMPD1',
 'DNPEP',
 'PHKG1',
 'SERPINC1',
 'ACTA1',
 'ABCB11',
 'MAPK4',
 'SERPINF2',
 'MPL',
 'EPHA5',
 'MT3',
 'KDR',
 'PSMB2',
 'ACSL4',
 'HTR1F',
 'PTH2R',
 'MTAP',
 'EIF6',
 'TOP2B',
 'CALM3',
 'C1QBP',
 'GRM1',
 'PIPOX',
 'HSPA5',
 'MAEA',
 'GPT',
 'EPHA4',
 'ARF1',
 'STIP1',
 'B2M',
 'GHSR',
 'RORB',
 'GLUL',
 'HSD17B7',
 'KCNJ15',
 'GATM',
 'HSD11B2',
 'EPHA3',
 'FGFR1',
 'HPX',
 'CA1',
 'CALY',
 'KCNJ6',
 'EGLN2',
 'MATK',
 'RDH13',
 'RARG',
 'GCLC',
 'ACY1',
 'EPHB6',
 'GRIA3',
 'CACNB1',
 'S100B',
 'KCNN3',
 'MAP2K5',
 'GLRA1',
 'SERPIND1',
 'JUP',
 'SERPINA3',
 'CA12',
 'MAP1A',
 'F11',
 'KCNH7',
 'PAK6',
 'AURKA',
 'SLC1A6',
 'VEGFA',
 'KCNA5',
 'FGA',
 'MYLK2',
 'NSDHL',
 'LMAN1',
 'GABRB1',
 'APOC3',
 'CANX',
 'TACR1',
 'PLD1',
 'SSTR2',
 'HCRT',
 'HTR2A',
 'NNT',
 'DGKD',
 'FCGR3A',
 'ROCK1',
 'FNTB',
 'SCNN1D',
 'FTH1',
 'S100A2',
 'PTGIS',
 'CYP2E1',
 'EGF',
 'APOA1',
 'AGT',
 'LRG1',
 'APCS',
 'NR0B1',
 'LIMK1',
 'RAC1',
 'GSTM1',
 'NUCB2',
 'BLVRA',
 'GJA1',
 'PRKAG2',
 'AHSP',
 'TGM2',
 'PCNA',
 'TTK',
 'KRT10',
 'ATP1B1',
 'CA13',
 'ALDH3B2',
 'PCCB',
 'ANXA4',
 'MAP3K12',
 'ACVR1B',
 'ITPA',
 'HPR',
 'F5',
 'LRP2',
 'PSMB10',
 'SDHA',
 'ALDH18A1',
 'PGF',
 'GLO1',
 'CMTR1',
 'CRH',
 'IGHA1',
 'STK39',
 'AQP3',
 'RAMP3',
 'ORM1',
 'SLC25A6',
 'NECTIN4',
 'VCAN',
 'CADPS',
 'CCS',
 'MAPK8IP1',
 'EDNRA',
 'GRIN2D',
 'CDC42BPG',
 'HPGDS',
 'CHRNB2',
 'CKMT1A',
 'FARSB',
 'MAPK13',
 'MAP4',
 'SEPSECS',
 'CFH',
 'FOLH1',
 'PYGB',
 'CDK4',
 'CTPS1',
 'MDH2',
 'FTL',
 'PLK3',
 'DLG4',
 'ACE2',
 'SF3A2',
 'CBX5',
 'ADRA1D',
 'CACNA1F',
 'RPS19',
 'IDH3A',
 'RRM2B',
 'TSLP',
 'SLC1A3',
 'CSTB',
 'HDAC9',
 'DRD2',
 'CA6',
 'CREB1',
 'SNRPD2',
 'GAPDHS',
 'SLC22A6',
 'PNP',
 'CYB5A',
 'LDHB',
 'AZGP1',
 'LTC4S',
 'SOAT1',
 'APOBEC1',
 'CYP3A7',
 'CROT',
 'SLC8A1',
 'CYP2C9',
 'KRAS',
 'ITIH3',
 'RPL35',
 'IMPA2',
 'NISCH',
 'CHRM3',
 'SLC16A2',
 'RPS17',
 'SPTLC1',
 'HGF',
 'APOL1',
 'PRNP',
 'TARS2',
 'HBA1',
 'P2RX4',
 'ALB',
 'CES1',
 'LDHC',
 'TNNC2',
 'LDHAL6B',
 'RPS6KA1',
 'KCNJ3',
 'IRAK1',
 'BHMT',
 'SREBF1',
 'SDS',
 'SULT2B1',
 'PLEKHA1',
 'ETFDH',
 'CA3',
 'MGMT',
 'NPR1',
 'GSTM5',
 'ADH5',
 'CYP1A2',
 'CNR2',
 'DAPK1',
 'NUAK1',
 'CACNA1D',
 'GRIN3B',
 'MDH1',
 'HTATIP2',
 'AMY2B',
 'KRTAP5-2',
 'AMY2A',
 'NME1',
 'RPS9',
 'HTR1B',
 'SLC12A4',
 'IL1A',
 'PNLIP',
 'ALAS1',
 'GABRB3',
 'ATP2A2',
 'ACAA2',
 'HNRNPD',
 'ACACA',
 'CD1A',
 'SLC25A4',
 'CD3G',
 'PPARD',
 'RPL23A',
 'MUSK']

In [ ]:
## This gives the indices for the train and test split
RA_data_split.keys()

dict_keys(['pos_train_indices', 'pos_test_indices', 'neg_train_indices', 'neg_test_indices'])

In [15]:
RA_data_negative.keys()

dict_keys(['EFO_0000685'])

In [17]:
RA_data_negative["EFO_0000685"].keys()

dict_keys(['epithelial cell of lacrimal sac', 'fast muscle cell', 'regulatory t cell', 'cardiac muscle cell', 'conjunctival epithelial cell', 'myometrial cell', 'large intestine goblet cell', 'respiratory mucous cell', 'fibroblast of breast', 'muscle cell', 'paneth cell of epithelium of large intestine', 'myeloid cell', 'club cell of prostate epithelium', 'epithelial cell', 'capillary endothelial cell', 'type ii pneumocyte', 'serous cell of epithelium of bronchus', 'cd4-positive helper t cell', 'bladder urothelial cell', 'dn4 thymocyte', 'pancreatic beta cell', 'ciliary body', 'cd8-positive, alpha-beta cytokine secreting effector t cell', 'endothelial cell of lymphatic vessel', 'lymphatic endothelial cell', 'duct epithelial cell', 'respiratory goblet cell', 'double-positive, alpha-beta thymocyte', 'hillock cell of prostate epithelium', 'acinar cell of salivary gland', 'type i nk t cell', 'radial glial cell', 'non-classical monocyte', 'pancreatic ductal cell', 'duodenum glandular cell', 'fibroblast', 'eye photoreceptor cell', 'myofibroblast cell', 'cd1c-positive myeloid dendritic cell', 'ciliated cell', 'transit amplifying cell of large intestine', 'sperm', 'stromal cell', 'myoepithelial cell', 'pulmonary ionocyte', 'langerhans cell', 'tendon cell', 'intestinal tuft cell', 'mesothelial cell', 'transit amplifying cell of small intestine', 'basal cell', 'microglial cell', 'naive regulatory t cell', 'endothelial cell of vascular tree', 'retinal ganglion cell', 'cd8-positive, alpha-beta cytotoxic t cell', 'hepatocyte', 'pericyte cell', 'fibroblast of cardiac tissue', 'liver dendritic cell', 'pancreatic pp cell', 'goblet cell', 'ionocyte', 't follicular helper cell', 'plasma cell', 'epithelial cell of uterus', 'cardiac endothelial cell', 'endothelial cell of hepatic sinusoid', 'alveolar fibroblast', 'ocular surface cell', 'small intestine goblet cell', 'erythroid progenitor', 'skeletal muscle satellite stem cell', 'myeloid dendritic cell', 'dendritic cell', 'intestinal crypt stem cell', 'dn3 thymocyte', 'limbal stem cell', 'adventitial cell', 'cd141-positive myeloid dendritic cell', 'enterocyte of epithelium of large intestine', 'enterocyte of epithelium of small intestine', 'immune cell', 'myeloid progenitor', 'plasmablast', 'kidney epithelial cell', 'intrahepatic cholangiocyte', 'retina horizontal cell', 'plasmacytoid dendritic cell', 'tracheal goblet cell', 'club cell', 'cd4-positive, alpha-beta memory t cell', 'vascular associated smooth muscle cell', 'cell of skeletal muscle', 'type i pneumocyte', 'medullary thymic epithelial cell', 'mucus secreting cell', 'luminal epithelial cell of mammary gland', 'gut endothelial cell', 'serous cell of epithelium of trachea', 'immature natural killer cell', 'hematopoietic stem cell', 'nk cell', 'ciliated epithelial cell', 'retinal pigment epithelial cell', 'endothelial cell of artery', 'pancreatic alpha cell', 'nampt neutrophil', 'lung microvascular endothelial cell', 'bronchial smooth muscle cell', 'bronchial vessel endothelial cell', 'granulocyte', 'lacrimal gland functional unit cell', 'vein endothelial cell', 'muller cell', 'retinal bipolar neuron', 'schwann cell', 'endothelial cell', 'monocyte', 'pancreatic delta cell', 'luminal cell of prostate epithelium', 'corneal epithelial cell', 'limbal stromal cell', 'keratinocyte', 'intermediate monocyte', 'memory b cell', 'basal cell of prostate epithelium', 'lung ciliated cell', 'intestinal crypt stem cell of large intestine', 'intestinal crypt stem cell of small intestine', 'intestinal enteroendocrine cell', 'smooth muscle cell', 'pancreatic stellate cell', 'dn1 thymic pro-t cell', 'hillock-club cell of prostate epithelium', 'mature conventional dendritic cell', 'naive thymus-derived cd4-positive, alpha-beta t cell', 'secretory cell', 'adipocyte', 'melanocyte', 'salivary gland cell', 'corneal keratocyte', 'classical monocyte', 'paneth cell of epithelium of small intestine', 'tongue muscle cell', 'immature enterocyte', 'mature nk t cell', 'mesenchymal stem cell', 'retinal blood vessel endothelial cell', 'mature enterocyte', 'macrophage', 'artery endothelial cell', 'pancreatic acinar cell', 'connective tissue cell', 'b cell', 'cd24 neutrophil', 'global'])

In [4]:
all_apr_df.head()

,ID,Name,Gene Name,GenBank Protein ID,GenBank Gene ID,UniProt ID,Uniprot Title,PDB ID,GeneCard ID,GenAtlas ID,HGNC ID,Species,Drug IDs
0,1,Peptidoglycan synthase FtsI,ftsI,1574687.0,L42023,P45059,FTSI_HAEIN,NaN,NaN,NaN,NaN,Haemophilus influenzae (strain ATCC 51907 / DS...,DB00303
1,2,Histidine decarboxylase,HDC,32109.0,X54297,P19113,DCHS_HUMAN,4E1O,NaN,HDC,HGNC:4855,Humans,DB00114
2,3,"Glutaminase liver isoform, mitochondrial",GLS2,6650606.0,AF110330,Q9UI32,GLSL_HUMAN,4BQM,NaN,GLS2,HGNC:29570,Humans,DB00142
3,4,Coagulation factor XIII A chain,F13A1,182309.0,M22001,P00488,F13A_HUMAN,1EVU; 1EX0; 1F13; 1FIE; 1GGT; 1GGU; 1GGY; 1QRK...,NaN,F13A1,HGNC:3531,Humans,DB11300; DB11311; DB11571; DB13151
4,5,"Nitric oxide synthase, inducible",NOS2,292242.0,L09210,P35228,NOS2_HUMAN,1NSI; 2LL6; 2NSI; 3E7G; 3EJ8; 3HR4; 4CX7; 4NOS,NaN,NOS2A,HGNC:7873,Humans,DB01017; DB01110; DB01234; DB01381; DB08814; D...

In [5]:
disease_drug_evidence_df.head()

,diseaseFromSourceMappedId,diseaseId,targetId,targetFromSourceId,clinicalPhase,clinicalStatus,drugId,targetId_genename
0,EFO_0000685,EFO_0000685,ENSG00000005844,P20701,2,Completed,CHEMBL1201575,ITGAL
1,EFO_0000685,EFO_0000685,ENSG00000006210,P78423,2,Completed,CHEMBL4297942,CX3CL1
2,EFO_0000685,EFO_0000685,ENSG00000006210,P78423,2,Completed,CHEMBL4297942,CX3CL1
3,EFO_0000685,EFO_0000685,ENSG00000007171,P35228,2,Completed,DB12237,NOS2
4,EFO_0000685,EFO_0000685,ENSG00000007171,P35228,2,Completed,DB12237,NOS2